spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/notesdb
  web:
    # CORS configuration
    cors:
      allowed-origins: "*"
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"

server.port: 8080

logging.level:
  com.example.notesapp: DEBUG